DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:exit success
DEBUG:asyncio:Using selector: EpollSelector
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:exit success
DEBUG:asyncio:Using selector: EpollSelector
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:exit success
DEBUG:asyncio:Using selector: EpollSelector
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:exit success
DEBUG:asyncio:Using selector: EpollSelector
INFO:HandlerLogger:Exiting...
DEBUG:asyncio:Using selector: EpollSelector
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
DEBUG:asyncio:Using selector: EpollSelector
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
INFO:tornado.access:200 GET /api/getAllMembers (::1) 2.24ms
WARNING:tornado.access:404 GET /api/getActMembers (::1) 3.73ms
INFO:tornado.general:/opt/git/pm-web/pm-server-python/src/server.py modified; restarting server
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
ERROR:tornado.application:Uncaught exception GET /api/getActiveMembers (::1)
HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/getActiveMembers', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/mal/.local/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/git/pm-web/pm-server-python/src/server.py", line 36, in get
    log.info('%d records found' % len(data))
TypeError: object of type 'Cursor' has no len()
ERROR:tornado.access:500 GET /api/getActiveMembers (::1) 6.60ms
INFO:tornado.general:/opt/git/pm-web/pm-server-python/src/server.py modified; restarting server
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
ERROR:tornado.application:Uncaught exception GET /api/getActiveMembers (::1)
HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/getActiveMembers', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/mal/.local/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/git/pm-web/pm-server-python/src/server.py", line 37, in get
    data = list(data)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: mongodb"//localhost:27017: [Errno -2] Name or service not known
ERROR:tornado.access:500 GET /api/getActiveMembers (::1) 30271.11ms
INFO:HandlerLogger:Server exited
INFO:tornado.general:/opt/git/pm-web/pm-server-python/src/server.py modified; restarting server
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
ERROR:tornado.application:Uncaught exception GET /api/getActiveMembers (::1)
HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/getActiveMembers', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/mal/.local/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/git/pm-web/pm-server-python/src/server.py", line 37, in get
    data = list(data)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: mongodb"//localhost:27017: [Errno -2] Name or service not known
ERROR:tornado.access:500 GET /api/getActiveMembers (::1) 30268.91ms
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
ERROR:tornado.application:Uncaught exception GET /api/getActiveMembers (::1)
HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/getActiveMembers', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/mal/.local/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/git/pm-web/pm-server-python/src/server.py", line 36, in get
    data = list(client.PeriMeleon['Members'].find({"$or": [{'status': 'COMMUNING'}, {'status': 'NONCOMMUNING' }]}))
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: mongodb"//localhost:27017: [Errno -2] Name or service not known
ERROR:tornado.access:500 GET /api/getActiveMembers (::1) 30073.96ms
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
ERROR:tornado.application:Uncaught exception GET /api/getAllMembers (::1)
HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/getAllMembers', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/mal/.local/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/git/pm-web/pm-server-python/src/server.py", line 29, in get
    data = list(data)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: mongodb"//localhost:27017: [Errno -2] Name or service not known
ERROR:tornado.access:500 GET /api/getAllMembers (::1) 30019.55ms
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
ERROR:tornado.application:Uncaught exception GET /api/getAllMembers (::1)
HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/getAllMembers', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/mal/.local/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/git/pm-web/pm-server-python/src/server.py", line 29, in get
    data = list(data)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/mal/.local/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: mongodb"//127.0.0.1:27017: [Errno -2] Name or service not known
ERROR:tornado.access:500 GET /api/getAllMembers (::1) 30173.98ms
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:521 records found
INFO:tornado.access:200 GET /api/getAllMembers (::1) 10.47ms
INFO:HandlerLogger:131 records found
INFO:tornado.access:200 GET /api/getActiveMembers (::1) 7.00ms
INFO:tornado.general:/opt/git/pm-web/pm-server-python/src/server.py modified; restarting server
INFO:HandlerLogger:Server listening on port 8000
DEBUG:HandlerLogger:Get All Members
INFO:HandlerLogger:521 records found
ERROR:tornado.application:Uncaught exception GET /api/getMembers?scope=all (::1)
HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/getMembers?scope=all', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/mal/.local/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/git/pm-web/pm-server-python/src/server.py", line 47, in get
    self.write(json.dumps(data))
NameError: name 'json' is not defined
ERROR:tornado.access:500 GET /api/getMembers?scope=all (::1) 30.65ms
INFO:tornado.general:/opt/git/pm-web/pm-server-python/src/server.py modified; restarting server
INFO:HandlerLogger:Server listening on port 8000
DEBUG:HandlerLogger:Get All Members
INFO:HandlerLogger:521 records found
ERROR:tornado.application:Uncaught exception GET /api/getMembers?scope=all (::1)
HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/getMembers?scope=all', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/mal/.local/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/git/pm-web/pm-server-python/src/server.py", line 48, in get
    self.write(json.dumps(data))
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
ERROR:tornado.access:500 GET /api/getMembers?scope=all (::1) 35.31ms
INFO:tornado.general:/opt/git/pm-web/pm-server-python/src/server.py modified; restarting server
INFO:HandlerLogger:Server listening on port 8000
DEBUG:HandlerLogger:Get All Members
INFO:HandlerLogger:521 records found
INFO:tornado.access:200 GET /api/getMembers?scope=all (::1) 14.49ms
DEBUG:HandlerLogger:Get Active Members
INFO:HandlerLogger:131 records found
INFO:tornado.access:200 GET /api/getMembers?scope=active (::1) 16.23ms
DEBUG:HandlerLogger:Get All Members
INFO:HandlerLogger:521 records found
INFO:tornado.access:200 GET /api/getMembers?scope=all (::1) 40.76ms
ERROR:HandlerLogger:Invalid scope parameter allgg
WARNING:tornado.access:400 GET /api/getMembers?scope=allgg (::1) 0.40ms
INFO:tornado.general:/opt/git/pm-web/pm-server-python/src/server.py modified; restarting server
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
ERROR:HandlerLogger:Invalid scope parameter: allgg
WARNING:tornado.access:400 GET /api/getMembers?scope=allgg (::1) 0.43ms
DEBUG:HandlerLogger:Get All Members
INFO:HandlerLogger:521 records found
INFO:tornado.access:200 GET /api/getMembers?scope=all (::1) 15.73ms
DEBUG:HandlerLogger:Get All Members
INFO:HandlerLogger:521 records found
INFO:tornado.access:200 GET /api/getMembers?scope=all (::1) 35.71ms
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:Server exited
INFO:HandlerLogger:Server listening on port 8000
INFO:HandlerLogger:Exiting...
INFO:HandlerLogger:Server exited
